package com.ssm.dao.mapper;


import com.ssm.dao.model.DataDo;
import org.apache.ibatis.annotations.Param;

/**
 * @author 莫小阳
 */
public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    DataDo selectByKey(@Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    int insert(@Param("record") DataDo record);
}